### ISSUE TITLE
MENU NON-Responsive. #1416 still has problems

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#1541]
The fix of changing the onclick was not included in the RenderChildren function.
The tertiary level still non repsonsive.

Also, one must mouse click on the down  arrow SVG in order to open the submenu. One should be able to click anywhere on that level.

**Comment by ishitagupta94** [comment]
It has been fixed in one of the nightly build. Please try with official release (coming soon).

It is by design. Menu link will be disabled if click implemented anywhere.

**Comment by scottw12** [comment]
This is the issue I speak of.  http://somup.com/criYlDY3kS

**Comment by Gaganbird** [comment]
Please upgrade your Vanjaro to v1.1.0 and see if it works. You may download it from https://github.com/vanjarosoftware/Vanjaro.Platform/releases/tag/v1.1.0

**Comment by scottw12** [comment]
I am running V1.1.0 and still have the issue of when you are using the mobile menu you have to click directly on the arrow at the right of the menu to get it to open. The preferred operation is you should be able to click anywhere in the area of the menu item to open the submenu. I do believe that is the way bootstrap responds.

Also the third level will not open when the second level arrow is clicked. I would think the <a> could be moved to the container  instead of the just the svg. 

https://dev.jcesba.org  <--- this is a public address

http://somup.com/crjDqNY80H <- screen capture
