### ISSUE TITLE
Can't signin to the page

### ISSUE THREAD

**Issue by igor-bizi** [vanjarosoftware/Vanjaro.Platform#30]
After installing Vanjaro extension the Vanjago made a new signin page. After logout as superuser I cannot signin anymore. The web page won't show the signin dialog box when I select the login link on the page.
DNN 9.5.0
![V2-Annotation 2020-05-11 153847](https://user-images.githubusercontent.com/65033041/81568353-ee934980-939d-11ea-9d11-0d416b0a9c9d.png)
![V1-Annotation 2020-05-11 153847](https://user-images.githubusercontent.com/65033041/81568357-ef2be000-939d-11ea-9186-de4e90bc5c7f.png)

**Comment by meetmandeep** [comment]
Yes. We became aware of this issue immediately after the release of alpha 3. It was resolved and downloads were updated. 

Go ahead and re-download and re-install. That should resolve the issue. Repairing the extension will not be sufficient, you would need to install again.

**Comment by igor-bizi** [comment]
OK, thx.

Best regards
Igor

**Comment by igor-bizi** [comment]
OK, THX

**Comment by parasdaryanani** [comment]
This issue still occurs if you uninstall Vanjaro from extensions (DNN v9.6.1). The signin page goes blank and you can no longer login. Other than that, when uninstalling, at first the site breaks saying that vanjaro.common.dll cannot be loaded. After removing its entry from web.config, the site is back up and running but there are some vanjaro scheduled tasks remaining in DNN which show recurring errors in admin logs.

**Comment by meetmandeep** [comment]
Thanks for reporting this. 

We'll need to document the uninstall process. Once Vanjaro is uninstalled, all pages created with Vanjaro will not have any content and hence there is no way to login using Vanjaro Login Block. You can always login by simply appending ctl=login to the URL and then adding the core "Account Login" module to the page. 

Other issues have been logged at https://github.com/vanjarosoftware/Vanjaro.Platform/issues/36

**Comment by parasdaryanani** [comment]
Surprisingly, ctl=Login didn't work. Ended up fixing it by setting the Login Page column entry in the PortalLocalization table to _NULL_. After that site.com/login showed a login module automatically.

**Comment by meetmandeep** [comment]
Thanks @parasdaryanani 
I've udpated https://github.com/vanjarosoftware/Vanjaro.Platform/issues/36 with this information.
